# Generated by Django 3.0.8 on 2020-07-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=64)),
                ('Description', models.TextField()),
                ('Bid', models.FloatField()),
                ('Image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
