# Generated by Django 3.0.8 on 2020-07-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='Category',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
