# Generated by Django 3.0.8 on 2020-07-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20200715_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Category',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
