# Generated by Django 3.0.8 on 2020-07-14 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20200715_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Bid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='auctions.Bid'),
        ),
    ]
