# Generated by Django 3.0.8 on 2020-07-15 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200715_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='Active',
            field=models.BooleanField(default=True),
        ),
    ]
