# Generated by Django 3.0.8 on 2020-07-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_auto_20200715_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='action',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
