# Generated by Django 3.0.8 on 2020-07-15 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
