# Generated by Django 3.0.8 on 2020-07-16 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_auto_20200716_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='Bidding',
        ),
    ]
