# Generated by Django 3.0.8 on 2020-07-16 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_auto_20200717_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='Bid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='auctions.Bid'),
        ),
    ]
