# Generated by Django 3.1.3 on 2021-06-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_auto_20210626_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='contact_no',
            field=models.CharField(default=0, max_length=14),
        ),
    ]
